# Generated by Django 4.2.30 on 2026-08-13 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_projectzone_projecttoken'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectzone',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AddField(
            model_name='projectzone',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='projectzone',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='projects.project'),
        ),
        migrations.AddField(
            model_name='projectzone',
            name='x_position',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='projectzone',
            name='y_position',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='projectzone',
            name='code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='projectzone',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='projectzone',
            unique_together={('project', 'code')},
        ),
    ]
