# Generated by Django 4.2.30 on 2026-08-13 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_projectzone_options_projectzone_is_active_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projectzone',
            unique_together=set(),
        ),
    ]
