# Generated by Django 4.2.30 on 2026-08-13 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_projectvisual'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectRoad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('direction', models.CharField(default='forward', max_length=50)),
                ('speed', models.FloatField(default=1.0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_roads', to='projects.projectzone')),
                ('to_zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_roads', to='projects.projectzone')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('moved', 'Moved'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('assigned', 'Assigned'), ('completed', 'Completed')], default='moved', max_length=50)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movement_from', to='projects.projectzone')),
                ('to_zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movement_to', to='projects.projectzone')),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='projects.projecttoken')),
            ],
        ),
    ]
