# Generated by Django 4.2.30 on 2026-08-13 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_projectroad_projectmovement'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectVisual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('shape_type', models.CharField(choices=[('triangle', 'Triangle'), ('square', 'Square'), ('pentagon', 'Pentagon'), ('hexagon', 'Hexagon'), ('polygon', 'Polygon')], default='triangle', max_length=50)),
                ('color', models.CharField(default='blue', max_length=50)),
                ('size', models.PositiveIntegerField(default=1)),
                ('rotation', models.IntegerField(default=0)),
                ('visual_data', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('active', 'Active'), ('moving', 'Moving'), ('completed', 'Completed'), ('blocked', 'Blocked')], default='waiting', max_length=50)),
                ('position_x', models.FloatField(default=0)),
                ('position_y', models.FloatField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visual_objects', to='projects.projectzone')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visuals', to='projects.project')),
            ],
        ),
    ]
