# Generated by Django 4.2.30 on 2026-08-13 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subproject',
            name='sequence',
        ),
        migrations.RemoveField(
            model_name='subprojecttype',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='subprojecttype',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='subprojectdependency',
            name='dependency_type',
            field=models.CharField(choices=[('requires', 'Requires'), ('blocks', 'Blocks'), ('related', 'Related'), ('parallel', 'Parallel')], default='requires', max_length=50),
        ),
    ]
