# Generated by Django 4.2.30 on 2026-08-13 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_remove_subproject_sequence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subprojectdependency',
            name='delay_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subprojectdependency',
            name='is_blocking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subprojectdependency',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('blocked', 'Blocked')], default='active', max_length=50),
        ),
        migrations.AlterField(
            model_name='subprojectdependency',
            name='dependency_type',
            field=models.CharField(choices=[('requires', 'Requires'), ('blocks', 'Blocks'), ('influences', 'Influences'), ('optional', 'Optional'), ('parallel', 'Parallel')], default='requires', max_length=50),
        ),
    ]
