# Generated by Django 4.2.30 on 2026-09-29 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_projectassignment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectattachment',
            name='owner_role',
            field=models.CharField(choices=[('customer', 'Customer'), ('consultant', 'Consultant'), ('workshop', 'Workshop'), ('designer', 'Designer')], default='customer', max_length=30),
        ),
    ]
