# Generated by Django 4.2.30 on 2026-10-07 04:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0013_projectattachment_owner_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectattachment',
            name='owner_role',
            field=models.CharField(choices=[('customer', 'Customer'), ('consultant', 'Consultant'), ('workshop', 'Workshop'), ('designer', 'Designer'), ('company', 'Company')], default='customer', max_length=30),
        ),
        migrations.CreateModel(
            name='ProjectActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('project.created', 'Project created'), ('project.sent_to_consultant', 'Project sent to consultant'), ('project.consultant_claimed', 'Project claimed by consultant')], max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_activities', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['project', '-created_at'], name='projects_pr_project_7b6ff5_idx'), models.Index(fields=['event_type', '-created_at'], name='projects_pr_event_t_90122b_idx')],
            },
        ),
    ]
