# Generated by Django 4.2.30 on 2026-09-02 05:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenders', '0005_alter_paymentschedule_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenderAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('awarded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tender_awards', to=settings.AUTH_USER_MODEL)),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='awards', to='tenders.bid')),
                ('tender', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='award', to='tenders.tender')),
            ],
        ),
    ]
