# Generated by Django 4.2.30 on 2026-09-03 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0009_tenderroundevaluation'),
    ]

    operations = [
        migrations.AddField(
            model_name='tender',
            name='winner_bid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_tenders', to='tenders.bid'),
        ),
    ]
