# Generated by Django 4.2.30 on 2026-09-17 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0011_customertenderselection'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultantspecification',
            name='dimensions',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='consultantspecification',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tender/specifications/'),
        ),
        migrations.AddField(
            model_name='consultantspecification',
            name='material',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='consultantspecification',
            name='row_number',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
