# Generated by Django 4.2.30 on 2026-09-17 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0012_consultantspecification_dimensions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultantspecification',
            name='row_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
