# Generated by Django 4.2.30 on 2026-09-20 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0014_specificationattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='tender',
            name='standardization_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_customer', 'Pending Customer'), ('approved', 'Approved'), ('revision_requested', 'Revision Requested')], default='draft', max_length=30),
        ),
    ]
