# Generated by Django 4.2.30 on 2026-09-23 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0016_consultantspecification_customer_review_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tender',
            name='round_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='tender',
            name='scheduled_end_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tender',
            name='scheduled_start_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
