# Generated by Django 4.2.30 on 2026-09-24 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0017_tender_round_count_tender_scheduled_end_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='discount_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='bid',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='bid',
            name='final_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15),
        ),
    ]
