# Generated by Django 4.2.30 on 2026-09-24 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0018_bid_discount_amount_bid_discount_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('selected', 'Selected'), ('rejected', 'Rejected')], default='draft', max_length=30),
        ),
    ]
