# Generated by Django 4.2.30 on 2026-08-12 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_organizationapplication_organizationrole_and_more'),
    ]

    operations = [
    ]
