# Generated by Django 4.2.30 on 2026-08-27 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='description',
            new_name='technical_notes',
        ),
        migrations.AddField(
            model_name='bid',
            name='delivery_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bid',
            name='production_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bid',
            name='warranty_months',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
