# Generated by Django 4.2.30 on 2026-08-30 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_initial'),
        ('tenders', '0004_complete_tender_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentschedule',
            options={'ordering': ['stage_order']},
        ),
        migrations.AlterModelOptions(
            name='tenderround',
            options={'ordering': ['round_number']},
        ),
        migrations.AlterField(
            model_name='bid',
            name='workshop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tender_bids', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='biditem',
            name='availability',
            field=models.CharField(choices=[('available', 'Available'), ('unavailable', 'Unavailable')], default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='biditem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='biditem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='biditem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='consultantspecification',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='paymentschedule',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tenderparticipant',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tender_participations', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='tenderround',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tenderround',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('closed', 'Closed'), ('evaluated', 'Evaluated')], default='draft', max_length=30),
        ),
    ]
