# Generated by Django 4.2.30 on 2026-09-02 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0006_tenderaward'),
    ]

    operations = [
        migrations.AddField(
            model_name='tender',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tender',
            name='reveal_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tender',
            name='revealed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
