# Generated by Django 4.2.30 on 2026-09-02 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0007_tender_closed_at_tender_reveal_at_tender_revealed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tender',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('closed', 'Closed'), ('revealed', 'Revealed'), ('awarded', 'Awarded'), ('cancelled', 'Cancelled')], default='draft', max_length=50),
        ),
    ]
