# Generated by Django 4.2.30 on 2026-09-02 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0008_alter_tender_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenderRoundEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ranking', models.JSONField(default=list)),
                ('summary', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tender_round', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='tenders.tenderround')),
                ('winner_bid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='winning_evaluations', to='tenders.bid')),
            ],
        ),
    ]
