# Generated by Django 4.2.30 on 2026-09-06 06:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenders', '0010_tender_winner_bid'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerTenderSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('selected', 'Selected'), ('consultant_verified', 'Consultant Verified'), ('identity_revealed', 'Identity Revealed'), ('payment_pending', 'Payment Pending'), ('payment_confirmed', 'Payment Confirmed'), ('finalized', 'Finalized'), ('cancelled', 'Cancelled')], default='selected', max_length=30)),
                ('selected_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_selections', to='tenders.bid')),
                ('selected_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tender_selections', to=settings.AUTH_USER_MODEL)),
                ('tender', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_selection', to='tenders.tender')),
            ],
        ),
    ]
