# Generated by Django 4.2.30 on 2026-09-21 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0015_tender_standardization_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultantspecification',
            name='customer_review_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='consultantspecification',
            name='customer_review_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('revise', 'Revise')], default='pending', max_length=20),
        ),
    ]
