# Generated by Django 4.2.30 on 2026-09-24 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0019_bid_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenderparticipant',
            name='responded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenderparticipant',
            name='response_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=20),
        ),
    ]
