# Generated by Django 4.2.30 on 2026-10-06 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0020_tenderparticipant_responded_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('selected', 'Selected'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='draft', max_length=30),
        ),
    ]
