# Generated by Django 4.2.30 on 2026-09-28 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_initial'),
        ('access', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessrequest',
            name='created_membership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_requests', to='organizations.membership'),
        ),
        migrations.AddField(
            model_name='accessrequest',
            name='created_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_requests', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='accessrequest',
            name='organization_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
