// ============================================================
// FEEMAAS WORKSPACE ENGINE
// Version 8
//
// Architecture:
// ------------------------------------------------------------
// 1. Capacity Layer
//    - Exactly 5 initial customer triangles
//    - Each triangle represents one project capacity slot
//    - Consumed slots disappear from the palette
//
// 2. Workspace Layer
//    - 4 customer/workflow zones
//    - Central Decision Plaza
//    - Coordinate system
//
// 3. Project Visual Layer
//    - Real project shapes
//    - Persistent position
//    - Selection
//    - Drag
//    - Double-click project information
//
// 4. Decision Plaza
//    - A project can wait for consultant decision
//    - Consultant test controls are generated by JS
//    - Consultant can move project to a zone
//
// IMPORTANT:
// Capacity triangles and Project Visuals are NOT the same thing.
// ============================================================


// ============================================================
// API
// ============================================================

const API_URL =
    "http://127.0.0.1:8000/api/projects/";


// ============================================================
// GLOBAL STATE
// ============================================================

let currentProjects = [];

let currentProject = null;

let currentVisual = null;

let selectedVisualElement = null;

let draggedCapacityTriangle = null;

let isDragging = false;

let dragStartX = 0;
let dragStartY = 0;

let objectStartX = 0;
let objectStartY = 0;


// ============================================================
// WORKSPACE CONFIGURATION
// ============================================================

const SVG_WIDTH = 800;
const SVG_HEIGHT = 500;

const SVG_CENTER_X = SVG_WIDTH / 2;
const SVG_CENTER_Y = SVG_HEIGHT / 2;

const SVG_NS =
    "http://www.w3.org/2000/svg";


// ============================================================
// CENTRAL DECISION PLAZA
// ============================================================

const CENTRAL_PLAZA = {

    id: "DECISION",

    name: "DECISION PLAZA",

    x: SVG_CENTER_X,

    y: SVG_CENTER_Y,

    radius: 55

};


// ============================================================
// WORKSPACE ZONES
// ============================================================

const WORKSPACE_ZONES = [

    {
        id: "A",
        name: "ZONE 1",
        role: "customer",
        x: 40,
        y: 40,
        width: 300,
        height: 170,
        behavior: "neon"
    },

    {
        id: "B",
        name: "ZONE 2",
        role: "customer",
        x: 460,
        y: 40,
        width: 300,
        height: 170,
        behavior: "neon"
    },

    {
        id: "C",
        name: "ZONE 3",
        role: "customer",
        x: 40,
        y: 290,
        width: 300,
        height: 170,
        behavior: "neon"
    },

    {
        id: "D",
        name: "ZONE 4",
        role: "customer",
        x: 460,
        y: 290,
        width: 300,
        height: 170,
        behavior: "neon"
    }

];


// ============================================================
// INITIALIZATION
// ============================================================

document.addEventListener(
    "DOMContentLoaded",
    initializeWorkspace
);


async function initializeWorkspace() {

    console.log(
        "FEEMAAS Workspace: initializing V8..."
    );

    initializeCapacityTriangles();

    initializeWorkspaceDropZone();

    initializeProjectModal();

    initializeConsultantPanel();

    drawWorkspace();

    await loadProjects();

    console.log(
        "FEEMAAS Workspace: initialization complete."
    );

}


// ============================================================
// CAPACITY TRIANGLES
// ============================================================
//
// Exactly five triangles exist in the HTML.
//
// They represent:
// Slot 1
// Slot 2
// Slot 3
// Slot 4
// Slot 5
//
// A consumed slot is hidden.
// ============================================================

function initializeCapacityTriangles() {

    const triangles =
        document.querySelectorAll(
            ".capacity-triangle"
        );

    console.log(
        "FEEMAAS: Capacity triangles found:",
        triangles.length
    );

    if (!triangles.length) {

        console.warn(
            "FEEMAAS: No capacity triangles found."
        );

        return;

    }

    triangles.forEach(
        triangle => {

            triangle.setAttribute(
                "draggable",
                "true"
            );

            triangle.addEventListener(
                "dragstart",
                startCapacityDrag
            );

            triangle.addEventListener(
                "dragend",
                stopCapacityDrag
            );

            triangle.addEventListener(
                "click",
                () => {

                    selectCapacityTriangle(
                        triangle
                    );

                }
            );

            triangle.addEventListener(
                "dblclick",
                () => {

                    openProjectModal(
                        triangle
                    );

                }
            );

        }
    );

}


// ============================================================
// CAPACITY SELECTION
// ============================================================

function selectCapacityTriangle(
    triangle
) {

    const triangles =
        document.querySelectorAll(
            ".capacity-triangle"
        );

    triangles.forEach(
        item => {

            item.classList.remove(
                "selected"
            );

        }
    );

    triangle.classList.add(
        "selected"
    );

    console.log(
        "FEEMAAS: Capacity triangle selected:",
        triangle.dataset.slot
    );

}


// ============================================================
// CAPACITY DRAG START
// ============================================================

function startCapacityDrag(event) {

    draggedCapacityTriangle =
        event.currentTarget;

    const slot =
        draggedCapacityTriangle.dataset.slot;

    event.dataTransfer.effectAllowed =
        "copy";

    event.dataTransfer.setData(
        "text/plain",
        slot
    );

    selectCapacityTriangle(
        draggedCapacityTriangle
    );

    draggedCapacityTriangle.classList.add(
        "dragging"
    );

    console.log(
        "FEEMAAS: Capacity drag started:",
        slot
    );

}


// ============================================================
// CAPACITY DRAG END
// ============================================================

function stopCapacityDrag() {

    if (draggedCapacityTriangle) {

        draggedCapacityTriangle.classList.remove(
            "dragging"
        );

    }

    draggedCapacityTriangle =
        null;

}


// ============================================================
// WORKSPACE DROP ZONE
// ============================================================

function initializeWorkspaceDropZone() {

    const svg =
        document.getElementById(
            "visualCanvas"
        );

    if (!svg) {

        console.warn(
            "FEEMAAS: visualCanvas not found."
        );

        return;

    }

    svg.addEventListener(
        "dragover",
        handleWorkspaceDragOver
    );

    svg.addEventListener(
        "drop",
        handleWorkspaceDrop
    );

}


// ============================================================
// DRAG OVER WORKSPACE
// ============================================================

function handleWorkspaceDragOver(event) {

    event.preventDefault();

    event.dataTransfer.dropEffect =
        "copy";

}


// ============================================================
// WORKSPACE DROP
// ============================================================
//
// Possible destinations:
//
// 1. Zone 1
// 2. Zone 2
// 3. Zone 3
// 4. Zone 4
// 5. Central Decision Plaza
//
// Outside these areas = invalid.
// ============================================================

function handleWorkspaceDrop(event) {

    event.preventDefault();

    if (!draggedCapacityTriangle) {

        return;

    }

    const svg =
        document.getElementById(
            "visualCanvas"
        );

    if (!svg) {

        return;

    }

    const point =
        getSVGPoint(
            svg,
            event.clientX,
            event.clientY
        );

    const zone =
        detectPointZone(
            point.x,
            point.y
        );

    const isCentral =
        isPointInsideCentralPlaza(
            point.x,
            point.y
        );

    console.log(
        "FEEMAAS: Capacity dropped:",
        {
            slot:
                draggedCapacityTriangle.dataset.slot,

            x:
                point.x,

            y:
                point.y,

            zone:
                zone
                    ? zone.id
                    : null,

            central:
                isCentral
        }
    );

    if (!zone && !isCentral) {

        console.log(
            "FEEMAAS: Invalid drop location."
        );

        return;

    }

    const slot =
        Number(
            draggedCapacityTriangle.dataset.slot
        );

    window.pendingProjectCreation = {

        slot: slot,

        zoneId:
            zone
                ? zone.id
                : null,

        decisionPlaza:
            isCentral,

        position_x:
            Number(
                point.x -
                SVG_CENTER_X
            ),

        position_y:
            Number(
                point.y -
                SVG_CENTER_Y
            )

    };

    openProjectModal(
        draggedCapacityTriangle
    );

}


// ============================================================
// DETECT CUSTOMER ZONE
// ============================================================

function detectPointZone(
    x,
    y
) {

    for (
        const zone of WORKSPACE_ZONES
    ) {

        const inside =
            x >= zone.x &&
            x <= zone.x + zone.width &&
            y >= zone.y &&
            y <= zone.y + zone.height;

        if (inside) {

            return zone;

        }

    }

    return null;

}


// ============================================================
// CENTRAL PLAZA DETECTION
// ============================================================

function isPointInsideCentralPlaza(
    x,
    y
) {

    const dx =
        x -
        CENTRAL_PLAZA.x;

    const dy =
        y -
        CENTRAL_PLAZA.y;

    const distance =
        Math.sqrt(
            dx * dx +
            dy * dy
        );

    return (
        distance <=
        CENTRAL_PLAZA.radius
    );

}


// ============================================================
// PROJECT MODAL INITIALIZATION
// ============================================================

function initializeProjectModal() {

    const modal =
        document.getElementById(
            "projectModal"
        );

    const closeButton =
        document.getElementById(
            "closeModal"
        );

    const createButton =
        document.getElementById(
            "createProjectBtn"
        );

    if (!modal) {

        console.warn(
            "FEEMAAS: projectModal not found."
        );

        return;

    }

    if (closeButton) {

        closeButton.addEventListener(
            "click",
            closeProjectModal
        );

    }

    if (createButton) {

        createButton.addEventListener(
            "click",
            handleCreateProject
        );

    }

    modal.addEventListener(
        "click",
        event => {

            if (
                event.target === modal
            ) {

                closeProjectModal();

            }

        }
    );

}


// ============================================================
// OPEN PROJECT CREATION MODAL
// ============================================================

function openProjectModal(
    triangle = null
) {

    const modal =
        document.getElementById(
            "projectModal"
        );

    if (!modal) {

        console.warn(
            "FEEMAAS: projectModal not found."
        );

        return;

    }

    if (triangle) {

        selectCapacityTriangle(
            triangle
        );

        if (
            !window.pendingProjectCreation
        ) {

            window.pendingProjectCreation = {

                slot:
                    Number(
                        triangle.dataset.slot
                    ),

                zoneId:
                    null,

                decisionPlaza:
                    true,

                position_x:
                    0,

                position_y:
                    0

            };

        }

    }

    modal.classList.remove(
        "hidden"
    );

}


// ============================================================
// CLOSE CREATION MODAL
// ============================================================

function closeProjectModal() {

    const modal =
        document.getElementById(
            "projectModal"
        );

    if (!modal) {

        return;

    }

    modal.classList.add(
        "hidden"
    );

    window.pendingProjectCreation =
        null;

}


// ============================================================
// CREATE PROJECT
// ============================================================

async function handleCreateProject() {

    const titleInput =
        document.getElementById(
            "projectTitleInput"
        );

    const descriptionInput =
        document.getElementById(
            "projectDescriptionInput"
        );

    const quantityInput =
        document.getElementById(
            "projectQuantityInput"
        );

    const budgetInput =
        document.getElementById(
            "projectBudgetInput"
        );

    const pending =
        window.pendingProjectCreation;

    if (!pending) {

        alert(
            "ابتدا یک مثلث پروژه را انتخاب کنید."
        );

        return;

    }

    const title =
        titleInput
            ? titleInput.value.trim()
            : "";

    const description =
        descriptionInput
            ? descriptionInput.value.trim()
            : "";

    const quantity =
        quantityInput
            ? quantityInput.value
            : "";

    const budget =
        budgetInput
            ? budgetInput.value
            : "";

    if (!title) {

        alert(
            "لطفاً نام پروژه را وارد کنید."
        );

        return;

    }

    const payload = {

        title: title,

        description: description,

        customer: 1,

        created_by: 1,

        status: "draft"

    };

    console.log(
        "FEEMAAS: Creating project",
        {
            payload,
            pending,
            quantity,
            budget
        }
    );

    try {

        const response =
            await fetch(
                API_URL,
                {

                    method: "POST",

                    headers: {

                        "Content-Type":
                            "application/json"

                    },

                    body:
                        JSON.stringify(
                            payload
                        )

                }
            );

        if (!response.ok) {

            throw new Error(
                `Project creation failed: ${response.status}`
            );

        }

        const project =
            await response.json();

        console.log(
            "FEEMAAS: Project created:",
            project
        );

        currentProject =
            project;

        closeProjectModal();

        /*
         * The backend currently creates the
         * initial visual automatically.
         *
         * Therefore we now locate that visual
         * and synchronize:
         *
         * - capacity slot
         * - position
         */

        const projectWithVisual =
            await fetchProjectById(
                project.id
            );

        if (
            projectWithVisual
        ) {

            const visual =
                getFirstProjectVisual(
                    projectWithVisual
                );

            if (visual) {

                await synchronizeNewVisual(
                    visual,
                    pending
                );

            }

        }

        alert(
            "پروژه با موفقیت ثبت شد"
        );

        /*
         * Reload projects without
         * resetting capacity state incorrectly.
         */

        await loadProjects();

    }

    catch (error) {

        console.error(
            "FEEMAAS Create Project Error:",
            error
        );

        alert(
            "خطا در ثبت پروژه"
        );

    }

}


// ============================================================
// FETCH SINGLE PROJECT
// ============================================================

async function fetchProjectById(
    projectId
) {

    try {

        const response =
            await fetch(
                `${API_URL}${projectId}/`
            );

        if (!response.ok) {

            return null;

        }

        return await response.json();

    }

    catch (error) {

        console.error(
            "FEEMAAS: Project fetch error:",
            error
        );

        return null;

    }

}


// ============================================================
// GET FIRST VISUAL
// ============================================================

function getFirstProjectVisual(
    project
) {

    if (
        !project ||
        !Array.isArray(
            project.zones
        )
    ) {

        return null;

    }

    for (
        const zone of project.zones
    ) {

        if (
            !zone ||
            !Array.isArray(
                zone.visuals
            )
        ) {

            continue;

        }

        if (
            zone.visuals.length
        ) {

            return zone.visuals[0];

        }

    }

    return null;

}


// ============================================================
// SYNCHRONIZE NEW VISUAL
// ============================================================
//
// This is important because the current
// backend automatically creates the visual.
//
// We PATCH it immediately so the visual
// represents the actual capacity slot
// and actual drop position.
// ============================================================

async function synchronizeNewVisual(
    visual,
    pending
) {

    if (
        !visual ||
        !visual.id ||
        !pending
    ) {

        return;

    }

    const payload = {

        position_x:
            Number(
                pending.position_x
            ),

        position_y:
            Number(
                pending.position_y
            ),

        visual_data: {

            ...(visual.visual_data || {}),

            capacity_slot:
                Number(
                    pending.slot
                ),

            engine_version:
                "phase_2_v8",

            workspace_location:
                pending.decisionPlaza
                    ? "decision_plaza"
                    : "zone",

            workspace_zone:
                pending.zoneId || null

        }

    };

    try {

        const response =
            await fetch(
                `${API_URL}visuals/${visual.id}/`,
                {

                    method: "PATCH",

                    headers: {

                        "Content-Type":
                            "application/json"

                    },

                    body:
                        JSON.stringify(
                            payload
                        )

                }
            );

        if (!response.ok) {

            console.warn(
                "FEEMAAS: Visual synchronization failed:",
                response.status
            );

            return;

        }

        console.log(
            "FEEMAAS: New visual synchronized."
        );

    }

    catch (error) {

        console.error(
            "FEEMAAS: Visual synchronization error:",
            error
        );

    }

}


// ============================================================
// LOAD ALL PROJECTS
// ============================================================

async function loadProjects() {

    try {

        const response =
            await fetch(
                API_URL
            );

        if (!response.ok) {

            throw new Error(
                `API error: ${response.status}`
            );

        }

        const projects =
            await response.json();

        if (
            !Array.isArray(
                projects
            )
        ) {

            throw new Error(
                "Projects response is not an array."
            );

        }

        currentProjects =
            projects;

        console.log(
            "FEEMAAS: Projects loaded:",
            currentProjects
        );

        /*
         * IMPORTANT:
         *
         * Do not redraw the entire page
         * in a way that resets capacity
         * or visual state.
         */

        renderWorkspaceState();

    }

    catch (error) {

        console.error(
            "FEEMAAS API Error:",
            error
        );

        /*
         * Workspace itself must still work
         * even if API is temporarily unavailable.
         */

        renderWorkspaceState();

    }

}


// ============================================================
// RENDER COMPLETE WORKSPACE STATE
// ============================================================

function renderWorkspaceState() {

    drawWorkspace();

    updateCapacityAvailability();

    renderAllProjectVisuals();

}


// ============================================================
// UPDATE CAPACITY AVAILABILITY
// ============================================================
//
// A slot is consumed if a backend project
// contains a visual whose visual_data.capacity_slot
// equals that slot.
// ============================================================

function updateCapacityAvailability() {

    const consumedSlots =
        new Set();

    currentProjects.forEach(
        project => {

            const visuals =
                getProjectVisuals(
                    project
                );

            visuals.forEach(
                visual => {

                    const slot =
                        Number(
                            visual &&
                            visual.visual_data
                                ? visual.visual_data.capacity_slot
                                : NaN
                        );

                    if (
                        Number.isFinite(
                            slot
                        ) &&
                        slot >= 1 &&
                        slot <= 5
                    ) {

                        consumedSlots.add(
                            slot
                        );

                    }

                }
            );

        }
    );

    const triangles =
        document.querySelectorAll(
            ".capacity-triangle"
        );

    triangles.forEach(
        triangle => {

            const slot =
                Number(
                    triangle.dataset.slot
                );

            if (
                consumedSlots.has(
                    slot
                )
            ) {

                triangle.classList.add(
                    "capacity-consumed"
                );

                triangle.setAttribute(
                    "data-consumed",
                    "true"
                );

                /*
                 * Hide consumed capacity.
                 */

                triangle.style.display =
                    "none";

            }

            else {

                triangle.classList.remove(
                    "capacity-consumed"
                );

                triangle.setAttribute(
                    "data-consumed",
                    "false"
                );

                triangle.style.display =
                    "";

            }

        }
    );

    console.log(
        "FEEMAAS: Consumed capacity slots:",
        Array.from(
            consumedSlots
        )
    );

}


// ============================================================
// GET ALL PROJECT VISUALS
// ============================================================

function getProjectVisuals(
    project
) {

    const result = [];

    if (
        !project ||
        !Array.isArray(
            project.zones
        )
    ) {

        return result;

    }

    project.zones.forEach(
        zone => {

            if (
                !zone ||
                !Array.isArray(
                    zone.visuals
                )
            ) {

                return;

            }

            zone.visuals.forEach(
                visual => {

                    if (visual) {

                        result.push(
                            visual
                        );

                    }

                }
            );

        }
    );

    return result;

}


// ============================================================
// RENDER ALL PROJECT VISUALS
// ============================================================

function renderAllProjectVisuals() {

    const svg =
        document.getElementById(
            "visualCanvas"
        );

    if (!svg) {

        return;

    }

    removeExistingVisuals(
        svg
    );

    currentProjects.forEach(
        project => {

            const visuals =
                getProjectVisuals(
                    project
                );

            visuals.forEach(
                visual => {

                    drawVisual(
                        visual,
                        false
                    );

                }
            );

        }
    );

}


// ============================================================
// DRAW WORKSPACE
// ============================================================

function drawWorkspace() {

    const svg =
        document.getElementById(
            "visualCanvas"
        );

    if (!svg) {

        console.warn(
            "FEEMAAS: visualCanvas not found."
        );

        return;

    }

    /*
     * This function draws ONLY infrastructure.
     *
     * It does NOT draw projects.
     * It does NOT draw capacity triangles.
     */

    svg.innerHTML = "";

    svg.setAttribute(
        "viewBox",
        `0 0 ${SVG_WIDTH} ${SVG_HEIGHT}`
    );

    drawBackground(
        svg
    );

    drawCoordinateSystem(
        svg
    );

    WORKSPACE_ZONES.forEach(
        zone => {

            drawZone(
                svg,
                zone
            );

        }
    );

    drawCentralPlaza(
        svg
    );

}


// ============================================================
// DRAW BACKGROUND
// ============================================================

function drawBackground(
    svg
) {

    const background =
        document.createElementNS(
            SVG_NS,
            "rect"
        );

    background.setAttribute(
        "x",
        "0"
    );

    background.setAttribute(
        "y",
        "0"
    );

    background.setAttribute(
        "width",
        SVG_WIDTH
    );

    background.setAttribute(
        "height",
        SVG_HEIGHT
    );

    background.setAttribute(
        "fill",
        "#f8fafc"
    );

    background.setAttribute(
        "rx",
        "18"
    );

    background.setAttribute(
        "data-workspace-background",
        "true"
    );

    svg.appendChild(
        background
    );

}


// ============================================================
// DRAW COORDINATE SYSTEM
// ============================================================

function drawCoordinateSystem(
    svg
) {

    const horizontal =
        document.createElementNS(
            SVG_NS,
            "line"
        );

    horizontal.setAttribute(
        "x1",
        "0"
    );

    horizontal.setAttribute(
        "y1",
        SVG_CENTER_Y
    );

    horizontal.setAttribute(
        "x2",
        SVG_WIDTH
    );

    horizontal.setAttribute(
        "y2",
        SVG_CENTER_Y
    );

    horizontal.setAttribute(
        "stroke",
        "#cbd5e1"
    );

    horizontal.setAttribute(
        "stroke-width",
        "2"
    );

    horizontal.setAttribute(
        "pointer-events",
        "none"
    );

    svg.appendChild(
        horizontal
    );


    const vertical =
        document.createElementNS(
            SVG_NS,
            "line"
        );

    vertical.setAttribute(
        "x1",
        SVG_CENTER_X
    );

    vertical.setAttribute(
        "y1",
        "0"
    );

    vertical.setAttribute(
        "x2",
        SVG_CENTER_X
    );

    vertical.setAttribute(
        "y2",
        SVG_HEIGHT
    );

    vertical.setAttribute(
        "stroke",
        "#cbd5e1"
    );

    vertical.setAttribute(
        "stroke-width",
        "2"
    );

    vertical.setAttribute(
        "pointer-events",
        "none"
    );

    svg.appendChild(
        vertical
    );

}


// ============================================================
// DRAW CENTRAL DECISION PLAZA
// ============================================================

function drawCentralPlaza(
    svg
) {

    const circle =
        document.createElementNS(
            SVG_NS,
            "circle"
        );

    circle.setAttribute(
        "cx",
        CENTRAL_PLAZA.x
    );

    circle.setAttribute(
        "cy",
        CENTRAL_PLAZA.y
    );

    circle.setAttribute(
        "r",
        CENTRAL_PLAZA.radius
    );

    circle.setAttribute(
        "fill",
        "#ffffff"
    );

    circle.setAttribute(
        "stroke",
        "#38bdf8"
    );

    circle.setAttribute(
        "stroke-width",
        "4"
    );

    circle.setAttribute(
        "id",
        "consultantPlaza"
    );

    circle.setAttribute(
        "data-plaza",
        "decision"
    );

    circle.setAttribute(
        "pointer-events",
        "none"
    );

    svg.appendChild(
        circle
    );


    const label =
        document.createElementNS(
            SVG_NS,
            "text"
        );

    label.setAttribute(
        "x",
        CENTRAL_PLAZA.x
    );

    label.setAttribute(
        "y",
        CENTRAL_PLAZA.y + 5
    );

    label.setAttribute(
        "text-anchor",
        "middle"
    );

    label.setAttribute(
        "font-family",
        "Tahoma, Arial, sans-serif"
    );

    label.setAttribute(
        "font-size",
        "11"
    );

    label.setAttribute(
        "font-weight",
        "bold"
    );

    label.setAttribute(
        "fill",
        "#0284c7"
    );

    label.setAttribute(
        "pointer-events",
        "none"
    );

    label.textContent =
        "DECISION";

    svg.appendChild(
        label
    );

}


// ============================================================
// DRAW ZONE
// ============================================================

function drawZone(
    svg,
    zone
) {

    if (!zone) {

        return;

    }

    const group =
        document.createElementNS(
            SVG_NS,
            "g"
        );

    group.setAttribute(
        "data-zone-id",
        zone.id
    );

    group.setAttribute(
        "data-zone-role",
        zone.role || ""
    );


    const zoneRect =
        document.createElementNS(
            SVG_NS,
            "rect"
        );

    zoneRect.setAttribute(
        "x",
        zone.x
    );

    zoneRect.setAttribute(
        "y",
        zone.y
    );

    zoneRect.setAttribute(
        "width",
        zone.width
    );

    zoneRect.setAttribute(
        "height",
        zone.height
    );

    zoneRect.setAttribute(
        "rx",
        "24"
    );

    zoneRect.setAttribute(
        "fill",
        "rgba(255,255,255,0.45)"
    );

    zoneRect.setAttribute(
        "stroke",
        "#cbd5e1"
    );

    zoneRect.setAttribute(
        "stroke-width",
        "1"
    );

    zoneRect.setAttribute(
        "class",
        "workspace-zone"
    );

    zoneRect.setAttribute(
        "pointer-events",
        "none"
    );

    group.appendChild(
        zoneRect
    );


    const label =
        document.createElementNS(
            SVG_NS,
            "text"
        );

    label.setAttribute(
        "x",
        zone.x + 18
    );

    label.setAttribute(
        "y",
        zone.y + 28
    );

    label.setAttribute(
        "font-family",
        "Tahoma, Arial, sans-serif"
    );

    label.setAttribute(
        "font-size",
        "11"
    );

    label.setAttribute(
        "font-weight",
        "bold"
    );

    label.setAttribute(
        "fill",
        "#94a3b8"
    );

    label.setAttribute(
        "pointer-events",
        "none"
    );

    label.textContent =
        zone.name;

    group.appendChild(
        label
    );

    svg.appendChild(
        group
    );

}


// ============================================================
// DRAW PROJECT VISUAL
// ============================================================

function drawVisual(
    visual,
    clearExisting = true
) {

    if (!visual) {

        return;

    }

    const svg =
        document.getElementById(
            "visualCanvas"
        );

    if (!svg) {

        return;

    }

    if (clearExisting) {

        removeExistingVisuals(
            svg
        );

    }

    visual.position_x =
        clamp(
            Number(
                visual.position_x
            ) || 0,
            -350,
            350
        );

    visual.position_y =
        clamp(
            Number(
                visual.position_y
            ) || 0,
            -200,
            200
        );

    const shapeType =
        String(
            visual.shape_type || ""
        ).toLowerCase();

    currentVisual =
        visual;

    switch (shapeType) {

        case "triangle":

            createTriangle(
                svg,
                visual
            );

            break;

        case "square":

            createSquare(
                svg,
                visual
            );

            break;

        case "hexagon":

            createHexagon(
                svg,
                visual
            );

            break;

        default:

            console.warn(
                "FEEMAAS: Unsupported visual shape:",
                visual.shape_type
            );

    }

}


// ============================================================
// REMOVE PROJECT VISUALS
// ============================================================

function removeExistingVisuals(
    svg
) {

    const visuals =
        svg.querySelectorAll(
            "[data-visual-id]"
        );

    visuals.forEach(
        element => {

            element.remove();

        }
    );

    selectedVisualElement =
        null;

}


// ============================================================
// CREATE TRIANGLE
// ============================================================

function createTriangle(
    svg,
    visual
) {

    createPolygonVisual(
        svg,
        visual,
        3,
        -90
    );

}


// ============================================================
// CREATE SQUARE
// ============================================================

function createSquare(
    svg,
    visual
) {

    createPolygonVisual(
        svg,
        visual,
        4,
        45
    );

}


// ============================================================
// CREATE HEXAGON
// ============================================================

function createHexagon(
    svg,
    visual
) {

    createPolygonVisual(
        svg,
        visual,
        6,
        30
    );

}


// ============================================================
// CREATE GENERIC POLYGON
// ============================================================

function createPolygonVisual(
    svg,
    visual,
    sides,
    angleOffset
) {

    const size =
        Number(
            visual.size
        ) || 100;

    const x =
        Number(
            visual.position_x
        ) || 0;

    const y =
        Number(
            visual.position_y
        ) || 0;

    const rotation =
        Number(
            visual.rotation
        ) || 0;

    const centerX =
        SVG_CENTER_X + x;

    const centerY =
        SVG_CENTER_Y + y;

    const points =
        buildPolygonPoints(
            centerX,
            centerY,
            size,
            sides,
            angleOffset
        );

    const polygon =
        document.createElementNS(
            SVG_NS,
            "polygon"
        );

    polygon.setAttribute(
        "points",
        points
    );

    polygon.setAttribute(
        "fill",
        visual.color ||
            "#8B4513"
    );

    polygon.setAttribute(
        "stroke",
        "#5b3a20"
    );

    polygon.setAttribute(
        "stroke-width",
        "3"
    );

    polygon.setAttribute(
        "opacity",
        "0.9"
    );

    polygon.setAttribute(
        "data-visual-id",
        visual.id
    );

    polygon.setAttribute(
        "data-project-id",
        visual.project
    );

    polygon.setAttribute(
        "data-shape-type",
        visual.shape_type
    );

    polygon.setAttribute(
        "data-sides",
        sides
    );

    polygon.setAttribute(
        "data-angle-offset",
        angleOffset
    );

    polygon.setAttribute(
        "data-x",
        x
    );

    polygon.setAttribute(
        "data-y",
        y
    );

    polygon.style.cursor =
        "grab";

    polygon.setAttribute(
        "transform",
        `rotate(${rotation} ${centerX} ${centerY})`
    );


    // --------------------------------------------------------
    // Click = select project
    // --------------------------------------------------------

    polygon.addEventListener(
        "click",
        selectVisual
    );


    // --------------------------------------------------------
    // Double click = project information
    // --------------------------------------------------------

    polygon.addEventListener(
        "dblclick",
        event => {

            event.stopPropagation();

            openProjectInformation(
                visual
            );

        }
    );


    // --------------------------------------------------------
    // Mouse down = drag
    // --------------------------------------------------------

    polygon.addEventListener(
        "mousedown",
        startDrag
    );

    svg.appendChild(
        polygon
    );

    updateZoneState(
        visual
    );

}


// ============================================================
// BUILD POLYGON POINTS
// ============================================================

function buildPolygonPoints(
    centerX,
    centerY,
    size,
    sides,
    angleOffset
) {

    const radius =
        size / 2;

    const points = [];

    for (
        let i = 0;
        i < sides;
        i++
    ) {

        const angle =
            (
                angleOffset +
                (360 / sides) * i
            ) *
            Math.PI /
            180;

        const pointX =
            centerX +
            radius *
            Math.cos(angle);

        const pointY =
            centerY +
            radius *
            Math.sin(angle);

        points.push(
            `${pointX},${pointY}`
        );

    }

    return points.join(
        " "
    );

}


// ============================================================
// SELECT PROJECT VISUAL
// ============================================================

function selectVisual(
    event
) {

    event.stopPropagation();

    const element =
        event.currentTarget;

    if (
        selectedVisualElement &&
        selectedVisualElement !== element
    ) {

        restoreVisualAppearance(
            selectedVisualElement
        );

    }

    selectedVisualElement =
        element;

    selectedVisualElement.setAttribute(
        "stroke",
        "#2563eb"
    );

    selectedVisualElement.setAttribute(
        "stroke-width",
        "6"
    );

    selectedVisualElement.style.cursor =
        "grab";

    const visual =
        findVisualById(
            element.dataset.visualId
        );

    if (visual) {

        currentVisual =
            visual;

        showProjectInfo(
            findProjectByVisual(
                visual.id
            )
        );

    }

}


// ============================================================
// RESTORE VISUAL APPEARANCE
// ============================================================

function restoreVisualAppearance(
    element
) {

    if (!element) {

        return;

    }

    const visualId =
        element.getAttribute(
            "data-visual-id"
        );

    const visual =
        findVisualById(
            visualId
        );

    const zone =
        visual
            ? detectVisualZone(
                visual
            )
            : null;

    if (zone) {

        element.setAttribute(
            "stroke",
            "#22d3ee"
        );

        element.setAttribute(
            "stroke-width",
            "5"
        );

    }

    else {

        element.setAttribute(
            "stroke",
            "#5b3a20"
        );

        element.setAttribute(
            "stroke-width",
            "3"
        );

    }

}


// ============================================================
// START PROJECT VISUAL DRAG
// ============================================================

function startDrag(
    event
) {

    event.preventDefault();

    event.stopPropagation();

    const element =
        event.currentTarget;

    if (
        selectedVisualElement !==
        element
    ) {

        selectVisual(
            event
        );

    }

    currentVisual =
        findVisualById(
            element.dataset.visualId
        );

    if (!currentVisual) {

        return;

    }

    isDragging =
        true;

    const svg =
        document.getElementById(
            "visualCanvas"
        );

    if (!svg) {

        return;

    }

    const point =
        getSVGPoint(
            svg,
            event.clientX,
            event.clientY
        );

    dragStartX =
        point.x;

    dragStartY =
        point.y;

    objectStartX =
        Number(
            currentVisual.position_x
        ) || 0;

    objectStartY =
        Number(
            currentVisual.position_y
        ) || 0;

    element.style.cursor =
        "grabbing";

    document.addEventListener(
        "mousemove",
        dragVisual
    );

    document.addEventListener(
        "mouseup",
        stopDrag
    );

}


// ============================================================
// DRAG PROJECT VISUAL
// ============================================================

function dragVisual(
    event
) {

    if (!isDragging) {

        return;

    }

    if (
        !selectedVisualElement
    ) {

        return;

    }

    const svg =
        document.getElementById(
            "visualCanvas"
        );

    if (!svg) {

        return;

    }

    const point =
        getSVGPoint(
            svg,
            event.clientX,
            event.clientY
        );

    const deltaX =
        point.x -
        dragStartX;

    const deltaY =
        point.y -
        dragStartY;

    const newX =
        objectStartX +
        deltaX;

    const newY =
        objectStartY +
        deltaY;

    updateVisualPosition(
        selectedVisualElement,
        newX,
        newY
    );

}


// ============================================================
// UPDATE VISUAL POSITION
// ============================================================

function updateVisualPosition(
    visualElement,
    x,
    y
) {

    if (
        !visualElement ||
        !currentVisual
    ) {

        return;

    }

    const size =
        Number(
            currentVisual.size
        ) || 100;

    const radius =
        size / 2;

    const minX =
        -SVG_CENTER_X +
        radius;

    const maxX =
        SVG_CENTER_X -
        radius;

    const minY =
        -SVG_CENTER_Y +
        radius;

    const maxY =
        SVG_CENTER_Y -
        radius;

    x =
        clamp(
            x,
            minX,
            maxX
        );

    y =
        clamp(
            y,
            minY,
            maxY
        );

    const centerX =
        SVG_CENTER_X + x;

    const centerY =
        SVG_CENTER_Y + y;

    const rotation =
        Number(
            currentVisual.rotation
        ) || 0;

    const sides =
        Number(
            visualElement.dataset.sides
        ) || 3;

    const angleOffset =
        Number(
            visualElement.dataset.angleOffset
        ) || 0;

    const points =
        buildPolygonPoints(
            centerX,
            centerY,
            size,
            sides,
            angleOffset
        );

    visualElement.setAttribute(
        "points",
        points
    );

    visualElement.setAttribute(
        "transform",
        `rotate(${rotation} ${centerX} ${centerY})`
    );

    visualElement.dataset.x =
        x;

    visualElement.dataset.y =
        y;

    currentVisual.position_x =
        Number(
            x.toFixed(2)
        );

    currentVisual.position_y =
        Number(
            y.toFixed(2)
        );

    updateZoneState(
        currentVisual
    );

}


// ============================================================
// STOP PROJECT VISUAL DRAG
// ============================================================

async function stopDrag() {

    if (!isDragging) {

        return;

    }

    isDragging =
        false;

    if (
        selectedVisualElement
    ) {

        selectedVisualElement.style.cursor =
            "grab";

    }

    document.removeEventListener(
        "mousemove",
        dragVisual
    );

    document.removeEventListener(
        "mouseup",
        stopDrag
    );

    if (
        currentVisual &&
        currentVisual.id
    ) {

        await saveVisualPosition();

    }

}


// ============================================================
// SAVE VISUAL POSITION
// ============================================================

async function saveVisualPosition() {

    if (
        !currentVisual ||
        !currentVisual.id
    ) {

        return;

    }

    const visualId =
        currentVisual.id;

    const url =
        `${API_URL}visuals/${visualId}/`;

    const payload = {

        position_x:
            Number(
                currentVisual.position_x
            ),

        position_y:
            Number(
                currentVisual.position_y
            )

    };

    try {

        const response =
            await fetch(
                url,
                {

                    method:
                        "PATCH",

                    headers: {

                        "Content-Type":
                            "application/json"

                    },

                    body:
                        JSON.stringify(
                            payload
                        )

                }
            );

        if (!response.ok) {

            throw new Error(
                `Save failed: ${response.status}`
            );

        }

        const savedVisual =
            await response.json();

        /*
         * Replace local visual data
         * without redrawing the workspace.
         */

        updateLocalVisual(
            savedVisual
        );

        currentVisual =
            savedVisual;

        updateZoneState(
            currentVisual
        );

        console.log(
            "FEEMAAS: Visual saved:",
            savedVisual
        );

    }

    catch (error) {

        console.error(
            "FEEMAAS Save Error:",
            error
        );

    }

}


// ============================================================
// UPDATE LOCAL VISUAL
// ============================================================

function updateLocalVisual(
    savedVisual
) {

    if (!savedVisual) {

        return;

    }

    for (
        const project of currentProjects
    ) {

        const visuals =
            getProjectVisuals(
                project
            );

        const index =
            visuals.findIndex(
                visual =>
                    String(
                        visual.id
                    ) ===
                    String(
                        savedVisual.id
                    )
            );

        if (index !== -1) {

            /*
             * Find actual object and update
             * its properties.
             */

            for (
                const zone of project.zones
            ) {

                if (
                    !zone ||
                    !Array.isArray(
                        zone.visuals
                    )
                ) {

                    continue;

                }

                const visualIndex =
                    zone.visuals.findIndex(
                        visual =>
                            String(
                                visual.id
                            ) ===
                            String(
                                savedVisual.id
                            )
                    );

                if (
                    visualIndex !== -1
                ) {

                    zone.visuals[
                        visualIndex
                    ] =
                        savedVisual;

                    return;

                }

            }

        }

    }

}


// ============================================================
// DETECT VISUAL ZONE
// ============================================================

function detectVisualZone(
    visual
) {

    if (!visual) {

        return null;

    }

    const centerX =
        SVG_CENTER_X +
        Number(
            visual.position_x
        );

    const centerY =
        SVG_CENTER_Y +
        Number(
            visual.position_y
        );

    for (
        const zone of WORKSPACE_ZONES
    ) {

        const inside =
            centerX >= zone.x &&
            centerX <=
                zone.x + zone.width &&
            centerY >= zone.y &&
            centerY <=
                zone.y + zone.height;

        if (inside) {

            return zone;

        }

    }

    return null;

}


// ============================================================
// DETECT IF VISUAL IS IN DECISION PLAZA
// ============================================================

function isVisualInDecisionPlaza(
    visual
) {

    if (!visual) {

        return false;

    }

    const x =
        SVG_CENTER_X +
        Number(
            visual.position_x
        );

    const y =
        SVG_CENTER_Y +
        Number(
            visual.position_y
        );

    return isPointInsideCentralPlaza(
        x,
        y
    );

}


// ============================================================
// UPDATE ZONE STATE
// ============================================================

function updateZoneState(
    visual
) {

    if (!visual) {

        return;

    }

    const zone =
        detectVisualZone(
            visual
        );

    const inDecisionPlaza =
        isVisualInDecisionPlaza(
            visual
        );

    if (inDecisionPlaza) {

        applyDecisionPlazaBehavior(
            visual
        );

        return;

    }

    if (zone) {

        applyZoneBehavior(
            visual,
            zone
        );

        return;

    }

    resetZoneBehavior(
        visual
    );

}


// ============================================================
// FIND VISUAL ELEMENT
// ============================================================

function findVisualElement(
    visualId
) {

    if (
        visualId === null ||
        visualId === undefined
    ) {

        return null;

    }

    const elements =
        document.querySelectorAll(
            "[data-visual-id]"
        );

    for (
        const element of elements
    ) {

        if (
            String(
                element.dataset.visualId
            ) ===
            String(
                visualId
            )
        ) {

            return element;

        }

    }

    return null;

}


// ============================================================
// APPLY CUSTOMER ZONE BEHAVIOR
// ============================================================

function applyZoneBehavior(
    visual,
    zone
) {

    const visualElement =
        findVisualElement(
            visual.id
        );

    if (!visualElement) {

        return;

    }

    if (
        zone.behavior ===
        "neon"
    ) {

        if (
            selectedVisualElement ===
            visualElement
        ) {

            visualElement.setAttribute(
                "stroke",
                "#2563eb"
            );

            visualElement.setAttribute(
                "stroke-width",
                "6"
            );

        }

        else {

            visualElement.setAttribute(
                "stroke",
                "#22d3ee"
            );

            visualElement.setAttribute(
                "stroke-width",
                "5"
            );

        }

        visualElement.setAttribute(
            "filter",
            "drop-shadow(0 0 8px #22d3ee)"
        );

        visualElement.setAttribute(
            "data-active-zone",
            zone.id
        );

        visualElement.removeAttribute(
            "data-decision-plaza"
        );

    }

}


// ============================================================
// APPLY DECISION PLAZA BEHAVIOR
// ============================================================

function applyDecisionPlazaBehavior(
    visual
) {

    const visualElement =
        findVisualElement(
            visual.id
        );

    if (!visualElement) {

        return;

    }

    /*
     * Decision Plaza projects receive
     * a distinct visual state.
     */

    if (
        selectedVisualElement ===
        visualElement
    ) {

        visualElement.setAttribute(
            "stroke",
            "#2563eb"
        );

        visualElement.setAttribute(
            "stroke-width",
            "6"
        );

    }

    else {

        visualElement.setAttribute(
            "stroke",
            "#f59e0b"
        );

        visualElement.setAttribute(
            "stroke-width",
            "5"
        );

    }

    visualElement.setAttribute(
        "filter",
        "drop-shadow(0 0 10px #f59e0b)"
    );

    visualElement.setAttribute(
        "data-decision-plaza",
        "true"
    );

    visualElement.removeAttribute(
        "data-active-zone"
    );

}


// ============================================================
// RESET ZONE BEHAVIOR
// ============================================================

function resetZoneBehavior(
    visual
) {

    const visualElement =
        findVisualElement(
            visual.id
        );

    if (!visualElement) {

        return;

    }

    visualElement.removeAttribute(
        "filter"
    );

    visualElement.removeAttribute(
        "data-active-zone"
    );

    visualElement.removeAttribute(
        "data-decision-plaza"
    );

    if (
        selectedVisualElement ===
        visualElement
    ) {

        visualElement.setAttribute(
            "stroke",
            "#2563eb"
        );

        visualElement.setAttribute(
            "stroke-width",
            "6"
        );

    }

    else {

        visualElement.setAttribute(
            "stroke",
            "#5b3a20"
        );

        visualElement.setAttribute(
            "stroke-width",
            "3"
        );

    }

}


// ============================================================
// PROJECT INFORMATION
// ============================================================
//
// Double-clicking an existing Project Visual
// opens this information panel.
//
// This is NOT the creation modal.
// ============================================================

function openProjectInformation(
    visual
) {

    if (!visual) {

        return;

    }

    const project =
        findProjectByVisual(
            visual.id
        );

    if (!project) {

        console.warn(
            "FEEMAAS: Project for visual not found:",
            visual.id
        );

        return;

    }

    currentProject =
        project;

    currentVisual =
        visual;

    showProjectInformationPanel(
        project,
        visual
    );

}


// ============================================================
// FIND PROJECT BY VISUAL
// ============================================================

function findProjectByVisual(
    visualId
) {

    for (
        const project of currentProjects
    ) {

        const visuals =
            getProjectVisuals(
                project
            );

        const found =
            visuals.find(
                visual =>
                    String(
                        visual.id
                    ) ===
                    String(
                        visualId
                    )
            );

        if (found) {

            return project;

        }

    }

    return null;

}


// ============================================================
// FIND VISUAL BY ID
// ============================================================

function findVisualById(
    visualId
) {

    for (
        const project of currentProjects
    ) {

        const visuals =
            getProjectVisuals(
                project
            );

        const visual =
            visuals.find(
                item =>
                    String(
                        item.id
                    ) ===
                    String(
                        visualId
                    )
            );

        if (visual) {

            return visual;

        }

    }

    return null;

}


// ============================================================
// SHOW PROJECT INFO
// ============================================================

function showProjectInfo(
    project
) {

    if (!project) {

        return;

    }

    const projectTitle =
        document.getElementById(
            "projectTitle"
        );

    const projectDescription =
        document.getElementById(
            "projectDescription"
        );

    const zoneName =
        document.getElementById(
            "zoneName"
        );

    if (projectTitle) {

        projectTitle.innerText =
            project.title || "";

    }

    if (projectDescription) {

        projectDescription.innerText =
            project.description || "";

    }

    if (zoneName) {

        zoneName.innerText =
            getProjectLocationLabel(
                project
            );

    }

}


// ============================================================
// PROJECT LOCATION LABEL
// ============================================================

function getProjectLocationLabel(
    project
) {

    const visual =
        getFirstProjectVisual(
            project
        );

    if (!visual) {

        return "نامشخص";

    }

    if (
        isVisualInDecisionPlaza(
            visual
        )
    ) {

        return "میدان تصمیم‌گیری مشاور";

    }

    const zone =
        detectVisualZone(
            visual
        );

    if (zone) {

        return zone.name;

    }

    return "خارج از نواحی";

}


// ============================================================
// PROJECT INFORMATION PANEL
// ============================================================

function showProjectInformationPanel(
    project,
    visual
) {

    let panel =
        document.getElementById(
            "feemaasProjectInfoPanel"
        );

    if (!panel) {

        panel =
            createProjectInformationPanel();

    }

    const location =
        getProjectLocationLabel(
            project
        );

    const visualData =
        visual.visual_data || {};

    panel.innerHTML = `

        <div class="feemaas-panel-inner">

            <div class="feemaas-panel-header">

                <strong>
                    اطلاعات پروژه
                </strong>

                <button
                    type="button"
                    id="feemaasCloseInfo"
                >
                    ×
                </button>

            </div>

            <div class="feemaas-panel-body">

                <div>
                    <strong>پروژه:</strong>
                    ${escapeHtml(
                        project.title || "-"
                    )}
                </div>

                <div>
                    <strong>توضیحات:</strong>
                    ${escapeHtml(
                        project.description || "-"
                    )}
                </div>

                <div>
                    <strong>وضعیت:</strong>
                    ${escapeHtml(
                        project.status || "-"
                    )}
                </div>

                <div>
                    <strong>محل فعلی:</strong>
                    ${escapeHtml(
                        location
                    )}
                </div>

                <div>
                    <strong>شکل:</strong>
                    ${escapeHtml(
                        visual.shape_type || "-"
                    )}
                </div>

                <div>
                    <strong>Visual ID:</strong>
                    ${escapeHtml(
                        String(
                            visual.id
                        )
                    )}
                </div>

                <div>
                    <strong>Project ID:</strong>
                    ${escapeHtml(
                        String(
                            project.id
                        )
                    )}
                </div>

                <div>
                    <strong>Capacity Slot:</strong>
                    ${escapeHtml(
                        String(
                            visualData.capacity_slot ||
                            "-"
                        )
                    )}
                </div>

            </div>

        </div>

    `;

    panel.classList.remove(
        "hidden"
    );

    const closeButton =
        document.getElementById(
            "feemaasCloseInfo"
        );

    if (closeButton) {

        closeButton.onclick =
            () => {

                panel.classList.add(
                    "hidden"
                );

            };

    }

}


// ============================================================
// CREATE PROJECT INFORMATION PANEL
// ============================================================

function createProjectInformationPanel() {

    const panel =
        document.createElement(
            "div"
        );

    panel.id =
        "feemaasProjectInfoPanel";

    panel.className =
        "hidden";

    panel.style.position =
        "fixed";

    panel.style.top =
        "50%";

    panel.style.left =
        "50%";

    panel.style.transform =
        "translate(-50%, -50%)";

    panel.style.zIndex =
        "10000";

    panel.style.background =
        "#ffffff";

    panel.style.border =
        "1px solid #cbd5e1";

    panel.style.borderRadius =
        "16px";

    panel.style.padding =
        "0";

    panel.style.minWidth =
        "360px";

    panel.style.maxWidth =
        "500px";

    panel.style.boxShadow =
        "0 20px 50px rgba(0,0,0,0.2)";

    document.body.appendChild(
        panel
    );

    return panel;

}


// ============================================================
// CONSULTANT PANEL
// ============================================================
//
// Temporary Phase 1 consultant controls.
//
// These controls are intentionally generated
// by JavaScript so we can test the decision
// engine before building the final consultant UI.
// ============================================================

function initializeConsultantPanel() {

    let panel =
        document.getElementById(
            "feemaasConsultantPanel"
        );

    if (panel) {

        return;

    }

    panel =
        document.createElement(
            "div"
        );

    panel.id =
        "feemaasConsultantPanel";

    panel.className =
        "hidden";

    panel.style.position =
        "fixed";

    panel.style.right =
        "24px";

    panel.style.top =
        "24px";

    panel.style.zIndex =
        "9999";

    panel.style.background =
        "#ffffff";

    panel.style.border =
        "2px solid #f59e0b";

    panel.style.borderRadius =
        "16px";

    panel.style.padding =
        "16px";

    panel.style.minWidth =
        "260px";

    panel.style.boxShadow =
        "0 15px 40px rgba(0,0,0,0.15)";

    document.body.appendChild(
        panel
    );

}


// ============================================================
// OPEN CONSULTANT DECISION PANEL
// ============================================================

function openConsultantDecision(
    project,
    visual
) {

    if (
        !project ||
        !visual
    ) {

        return;

    }

    const panel =
        document.getElementById(
            "feemaasConsultantPanel"
        );

    if (!panel) {

        return;

    }

    panel.innerHTML = `

        <div>

            <strong>
                تصمیم مشاور
            </strong>

            <hr>

            <div style="margin-bottom:10px;">
                پروژه:
                <strong>
                    ${escapeHtml(
                        project.title || "-"
                    )}
                </strong>
            </div>

            <div style="margin-bottom:12px;">
                این پروژه فعلاً در میدان
                تصمیم‌گیری است.
            </div>

            <button
                type="button"
                data-consultant-zone="A"
            >
                انتقال به Zone 1
            </button>

            <button
                type="button"
                data-consultant-zone="B"
            >
                انتقال به Zone 2
            </button>

            <button
                type="button"
                data-consultant-zone="C"
            >
                انتقال به Zone 3
            </button>

            <button
                type="button"
                data-consultant-zone="D"
            >
                انتقال به Zone 4
            </button>

            <button
                type="button"
                id="feemaasCloseConsultant"
            >
                بستن
            </button>

        </div>

    `;

    panel.classList.remove(
        "hidden"
    );

    const buttons =
        panel.querySelectorAll(
            "[data-consultant-zone]"
        );

    buttons.forEach(
        button => {

            button.addEventListener(
                "click",
                () => {

                    const zoneId =
                        button.dataset.consultantZone;

                    moveProjectToZone(
                        project,
                        visual,
                        zoneId
                    );

                }
            );

        }
    );

    const closeButton =
        document.getElementById(
            "feemaasCloseConsultant"
        );

    if (closeButton) {

        closeButton.onclick =
            () => {

                panel.classList.add(
                    "hidden"
                );

            };

    }

}


// ============================================================
// MOVE PROJECT TO ZONE
// ============================================================
//
// Temporary consultant engine.
//
// For now we move the visual to the
// center of the selected zone and persist
// its position.
//
// Later this exact operation can be connected
// to a dedicated backend zone-assignment API.
// ============================================================

async function moveProjectToZone(
    project,
    visual,
    zoneId
) {

    const zone =
        WORKSPACE_ZONES.find(
            item =>
                item.id === zoneId
        );

    if (!zone) {

        return;

    }

    const newX =
        (
            zone.x +
            zone.width / 2
        ) -
        SVG_CENTER_X;

    const newY =
        (
            zone.y +
            zone.height / 2
        ) -
        SVG_CENTER_Y;

    visual.position_x =
        Number(
            newX.toFixed(2)
        );

    visual.position_y =
        Number(
            newY.toFixed(2)
        );

    const element =
        findVisualElement(
            visual.id
        );

    if (element) {

        updateVisualPosition(
            element,
            newX,
            newY
        );

    }

    await saveVisualPosition();

    const panel =
        document.getElementById(
            "feemaasConsultantPanel"
        );

    if (panel) {

        panel.classList.add(
            "hidden"
        );

    }

    console.log(
        "FEEMAAS Consultant decision:",
        {
            project:
                project.id,

            visual:
                visual.id,

            zone:
                zone.id
        }
    );

}


// ============================================================
// ESCAPE HTML
// ============================================================

function escapeHtml(
    value
) {

    return String(
        value
    )
        .replace(
            /&/g,
            "&amp;"
        )
        .replace(
            /</g,
            "&lt;"
        )
        .replace(
            />/g,
            "&gt;"
        )
        .replace(
            /"/g,
            "&quot;"
        )
        .replace(
            /'/g,
            "&#039;"
        );

}


// ============================================================
// SVG COORDINATES
// ============================================================

function getSVGPoint(
    svg,
    clientX,
    clientY
) {

    const rect =
        svg.getBoundingClientRect();

    const viewBox =
        svg.viewBox.baseVal;

    const viewBoxWidth =
        viewBox.width ||
        SVG_WIDTH;

    const viewBoxHeight =
        viewBox.height ||
        SVG_HEIGHT;

    const scaleX =
        viewBoxWidth /
        rect.width;

    const scaleY =
        viewBoxHeight /
        rect.height;

    return {

        x:
            (
                clientX -
                rect.left
            ) *
            scaleX,

        y:
            (
                clientY -
                rect.top
            ) *
            scaleY

    };

}


// ============================================================
// VISUAL INFORMATION PANEL
// ============================================================

function updateVisualPanel(
    visual
) {

    if (!visual) {

        return;

    }

    const visualName =
        document.getElementById(
            "visualName"
        );

    const visualType =
        document.getElementById(
            "visualType"
        );

    const visualMaterial =
        document.getElementById(
            "visualMaterial"
        );

    if (visualName) {

        visualName.innerText =
            "نام: " +
            (
                visual.name ||
                "-"
            );

    }

    if (visualType) {

        visualType.innerText =
            "نوع: " +
            (
                visual.shape_type ||
                "-"
            );

    }

    const material =
        visual.visual_data &&
        visual.visual_data.material
            ? visual.visual_data.material
            : "-";

    if (visualMaterial) {

        visualMaterial.innerText =
            "متریال: " +
            material;

    }

}


// ============================================================
// UTILITY
// ============================================================

function clamp(
    value,
    min,
    max
) {

    return Math.max(
        min,
        Math.min(
            max,
            value
        )
    );

}


// ============================================================
// LEGACY COMPATIBILITY
// ============================================================

function updateTrianglePosition(
    triangle,
    x,
    y
) {

    updateVisualPosition(
        triangle,
        x,
        y
    );

}


// ============================================================
// VERSION
// ============================================================

console.log(
    "FEEMAAS Workspace Engine Version 8 loaded."
);